source 'https://rubygems.org'

gem 'json'
gem 'net/http'
gem 'octokit', '~> 4.0'
gem 'sinatra'
gem 'haml'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'activerecord', '~> 4.2', '>= 4.2.6'
gem 'time_difference', ' ~> 0.4.2'